<a href="https://colab.research.google.com/github/mrsandy1965/DVA_Practice/blob/main/DVA_Numpy_Lec1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# row
arr[0]

array([1, 2, 3])

In [ ]:
# column
arr[:,0]

array([1, 4])

In [ ]:
# specifc element
arr[0,1]

np.int64(2)

In [ ]:
# step slicing
arr[1,::2]

array([4, 6])

In [ ]:
# negative step slicing
arr[::-1,::-1]

array([[6, 5, 4],
       [3, 2, 1]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# scalar operation
print(arr+5 , arr - 5 , arr*2 , arr/2 , arr%2 , sep="\n arr= ")


 arr= [[ 6  7  8]
 [ 9 10 11]]
 arr= [[-4 -3 -2]
 [-1  0  1]]
 arr= [[ 2  4  6]
 [ 8 10 12]]
 arr= [[0.5 1.  1.5]
 [2.  2.5 3. ]]
 arr= [[1 0 1]
 [0 1 0]]


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40,8]])
A + B

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
A + B

array([[11, 22],
       [33, 44]])

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[10,20,30],
              [40,50,60],
              [70,80,90],
              [100,110,120]])
A+B

ValueError: operands could not be broadcast together with shapes (2,3) (4,3) 

In [ ]:
# Broadcasting
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[10,20,30]])
A+B

array([[11, 22, 33],
       [14, 25, 36]])

In [ ]:
B = np.array([[10,20,30],
              [40,50,60],
              [70,80,90],
              [100,110,120]])
np.mean(B)
# B.mean()

np.float64(65.0)

In [ ]:
B = np.array([[10,20,30],
              [40,50,60],
              [70,80,90],
              [100,110,120]])
np.mean(B,axis = 0) # column
# B.mean(axis = 0)

array([55., 65., 75.])

In [ ]:
B>90

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [ ]:
(B>90).any(axis=1) # 0= column , 1= row

array([False, False, False,  True])

In [ ]:
# .any(axis = 0) -> atleast one True in each column
# .any(axis = 1) -> atleast one True in each row
# .all(axis = 0) -> all True in each column
# .all(axis = 1) -> all True in each row
print((B>90),(B>90).any(axis=0),(B>90).any(axis=1),(B>90).all(axis=0) , (B>90).all(axis=1) , sep="\n\n\n")

[[False False False]
 [False False False]
 [False False False]
 [ True  True  True]]


[ True  True  True]


[False False False  True]


[False False False]


[False False False  True]


In [ ]:
marks = np.array([40,50,60,40,30,20,90,100,70])
np.percentile(marks,90)

np.float64(92.0)

In [ ]:
A = np.array([[1,2,3,7],[4,5,6,8]])
B = np.array([[10,20,30],
              [40,50,60]])
print(A.shape)
B.shape

(2, 4)


(2, 3)

In [ ]:
np.dot(A,B)

ValueError: shapes (2,4) and (2,3) not aligned: 4 (dim 1) != 2 (dim 0)

In [ ]:
A@B

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [ ]:
A = np.array([[1,2,3,7],[4,5,6,8]])
B = np.array([[10,20,30],
              [40,50,60],
              [70,80,90],
              [100,110,120]])
A@B

array([[1000, 1130, 1260],
       [1460, 1690, 1920]])

In [ ]:
np.dot(A,B)

array([[1000, 1130, 1260],
       [1460, 1690, 1920]])

In [ ]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6],
       [7, 8]])